apiVersion: v1
kind: Service
metadata:
  name: resume-bot-service
spec:
  type: NodePort
  selector:
    app: resume-bot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
